{% set name = "rio-stac" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2146302819807eaaf7b93fe5f651405d7b20902c72ade8726fd3d28f73bf1be8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - stac=rio_stac.scripts.cli:stac

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.8
  run:
    - rasterio
    - python >=3.8
    - pystac >=1.0.0,<2.0.0

test:
  imports:
    - rio_stac
  commands:
    - pip check
    - stac --help
  requires:
    - pip

about:
  home: https://developmentseed.org/rio-stac/
  dev_url: https://github.com/developmentseed/rio-stac
  summary: Create STAC Items from raster datasets.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
