schema_version: 1

context:
  name: rio-stac
  version: "0.12.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 02cf7ff4e2228752277cfd08cca26d4f4f7253ded3b49fb1db3ea207050d7cda

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - stac=rio_stac.scripts.cli:stac

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python ${{ python_min }}.*
  run:
    - rasterio !=1.4.2,>=1.0
    - python >=${{ python_min }}
    - pystac >=1.0.0,<2.0.0

tests:
  - python:
      imports:
        - rio_stac
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - stac --help

about:
  summary: Create STAC Items from raster datasets.
  license: MIT
  license_file: LICENSE
  homepage: https://developmentseed.org/rio-stac/
  repository: https://github.com/developmentseed/rio-stac

extra:
  recipe-maintainers:
    - thewchan
